import { SqueezeCarousel } from "@/components/ui/carousel-squeeze";
import { thinkers } from "@/data/thinkers";

const background = "/HapiBG.png";

function Brand() { return <a className="hapi-brand" href="/" aria-label="HAPI home"><span className="hapi-brand-mark">✦</span><span>HAPI</span><small>Humanist Alliance<br />Philippines, International</small></a>; }
function SectionLabel({ children }: { children: React.ReactNode }) { return <p className="section-label"><span />{children}</p>; }

export default function HomePage() {
  return <main>
    <a className="skip-link" href="#main-content">Skip to content</a>
    <section className="conference-hero" style={{ "--hero-image": `url(${background})` } as React.CSSProperties}>
      <div className="hero-texture" aria-hidden="true" />
      <nav className="site-nav page-shell" aria-label="Primary navigation"><Brand /><div className="site-nav-links"><a href="#about">About the conference</a><a href="#thinkers">Thinkers</a><a className="nav-cta" href="/register">Register <span>↗</span></a></div></nav>
      <div className="hero-layout page-shell"><div className="hero-copy"><p className="conference-kicker">HAPI presents · 2026</p><h1>1st Secular<br /><em>Philosophical</em><br />Paper Conference</h1><div className="hero-rule" /><p className="hero-theme">Discarding God: Values in a Worldview Without Religion</p><div className="hero-details"><span>November 20, 2026</span><i /><span>The Ministry Lounge Bar &amp; Cafe, Makati City</span></div><a className="primary-cta" href="/register">Register for the Conference <span>↗</span></a></div><div className="hero-caption"><span>01</span><p>A gathering for rigorous thought, honest questions, and the values we build together.</p></div></div>
      <div className="hero-bottom page-shell"><span>Secular humanism / scholarship / community</span><a href="#about">Scroll to explore ↓</a></div>
    </section>
    <section className="about-section page-shell" id="about"><div className="about-intro"><SectionLabel>DID YOU KNOW?</SectionLabel></div><div className="about-copy"><p>The secular humanist movement has always been deeply rooted in scholarship, research, and academic work. It has been shaped by philosophers, scientists, historians, secular theologians, psychologists, and public intellectuals whose work transformed how we think about ethics, religion, politics, science, and the human condition.</p><p>Prominent figures such as Paul Kurtz, Bertrand Russell, John Dewey, A. J. Ayer, Daniel Dennett, B. F. Skinner, Karl Popper, Albert Einstein, Carl Sagan, Stephen Hawking, Corliss Lamont and Isaac Asimov - among many others - have helped shape the rich intellectual tradition from which contemporary and organizational secular humanism continues to grow.</p><p>All of these thinkers were once part of leading humanist organizations during their lifetime such as the American Humanist Association and Humanists UK, organizations that form part of (and founding member) of its global humanist community - Humanists International - which proudly supports this conference.</p><p>By participating in this event through HAPI, you join in the same movement these thinkers belonged to and become part of this continuing international intellectual tradition of rigorous, secular and evidence-based scholarship that seeks to better understand humanity, ethics, society, and our place in the world.</p><div className="invitation"><p>You do not need to be an academic.</p><p>You do not need to present a paper.</p><p>You only need to bring your curiosity, your questions, and your willingness to think.</p><p>Perhaps you will leave with answers.<br />Perhaps you will leave with better questions.</p><p>Either way, you will have taken part in the pursuit. 🔭</p></div><p className="see-more">See more of these thinkers below!</p></div></section>
    <section className="thinkers-section" id="thinkers"><div className="page-shell"><div className="thinkers-heading"><div><SectionLabel>THE INTELLECTUAL TRADITION</SectionLabel><h2>Thinkers who<br /><em>made room</em> for doubt.</h2></div><p>These are just a few of the many academics involved in secular humanist organizations. The final images and descriptions will be added as approved materials become available.</p></div><SqueezeCarousel slides={thinkers} label="Secular humanist thinkers" /></div></section>
    <section className="note-section page-shell"><span className="note-mark">↗</span><p>Please note that these are just a few among the many academics who are involved in a secular humanist organization and it does not include the recipients of secular humanist awards that were secular humanist in their principle/philosophy but not organizationally involved - one can be a secular humanist without organizational affiliation or involvement.</p></section>
    <section className="closing-section page-shell"><SectionLabel>MAKE SPACE FOR THE QUESTION</SectionLabel><h2>Bring your curiosity.<br /><em>Leave with better questions.</em></h2><a className="primary-cta" href="/register">Register for the Conference <span>↗</span></a></section>
    <footer className="site-footer"><div className="page-shell footer-inner"><Brand /><p>1st Secular Philosophical Paper Conference<br />November 20, 2026 · Makati City</p><span>© 2026 HAPI</span></div></footer>
  </main>;
}
