'use client';

import { useState } from 'react';

const initialForm = { lastName: '', firstName: '', middleName: '', gender: '', email: '', barangay: '', city: '', province: '', region: '', contactNumber: '', institutionalAffiliation: '', degreeProgram: '', otherAffiliations: '', religiousStance: '', religiousStanceOther: '', attendingAs: 'Participant/Audience', attendanceMode: '', consent: false };
const religiousOptions = ['Atheist', 'Agnostic', 'Deist', 'Pantheist/Panentheist', 'Secular/Non-Believer/Non-theistic', 'Non-Religious Believer', 'Curious Believer', 'Other'];
const attendanceOptions = ['Onsite', 'Online'];

function Field({ label, name, value, onChange, error, required = false, help, ...props }) {
  const errorId = `${name}-error`; const helpId = `${name}-help`;
  return <div className={`form-field${error ? ' has-error' : ''}`}><label htmlFor={name}>{label}{required && <span className="required-mark">*</span>}</label>{help && <p className="field-help" id={helpId}>{help}</p>}<input id={name} name={name} value={value} onChange={onChange} aria-invalid={Boolean(error)} aria-describedby={[help && helpId, error && errorId].filter(Boolean).join(' ') || undefined} {...props} />{error && <p className="field-error" id={errorId} role="alert">{error}</p>}</div>;
}

function TextareaField({ label, name, value, onChange, help, ...props }) { const helpId = `${name}-help`; return <div className="form-field"><label htmlFor={name}>{label}</label>{help && <p className="field-help" id={helpId}>{help}</p>}<textarea id={name} name={name} value={value} onChange={onChange} aria-describedby={help ? helpId : undefined} {...props} /></div>; }
function SelectField({ label, name, value, onChange, options, error, required = false, help }) { const errorId = `${name}-error`; const helpId = `${name}-help`; return <div className={`form-field${error ? ' has-error' : ''}`}><label htmlFor={name}>{label}{required && <span className="required-mark">*</span>}</label>{help && <p className="field-help" id={helpId}>{help}</p>}<select id={name} name={name} value={value} onChange={onChange} aria-invalid={Boolean(error)} aria-describedby={[help && helpId, error && errorId].filter(Boolean).join(' ') || undefined}><option value="">Select an option</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select>{error && <p className="field-error" id={errorId} role="alert">{error}</p>}</div>; }
function SectionHeading({ number, children }) { return <div className="form-section-heading"><span>{number}</span><h2>{children}</h2></div>; }

export default function RegistrationForm() {
  const [form, setForm] = useState(initialForm); const [errors, setErrors] = useState({}); const [status, setStatus] = useState({ type: 'idle', message: '' });
  const update = (event) => { const { name, value, type, checked } = event.target; setForm((current) => ({ ...current, [name]: type === 'checkbox' ? checked : value })); setErrors((current) => ({ ...current, [name]: '' })); };
  const validate = () => { const next = {}; ['lastName', 'firstName', 'gender', 'email', 'barangay', 'city', 'province', 'region', 'contactNumber', 'religiousStance', 'attendanceMode'].forEach((field) => { if (!String(form[field]).trim()) next[field] = 'This field is required.'; }); if (form.email && !/^\S+@\S+\.\S+$/.test(form.email.trim())) next.email = 'Enter a valid email address.'; if (form.contactNumber && !/^[+()\-\s\d]{7,20}$/.test(form.contactNumber.trim())) next.contactNumber = 'Enter a valid contact number.'; if (form.religiousStance === 'Other' && !form.religiousStanceOther.trim()) next.religiousStanceOther = 'Please specify your religious stance.'; if (!form.consent) next.consent = 'Please acknowledge the privacy notice to continue.'; setErrors(next); return next; };
  const submit = async (event) => { event.preventDefault(); if (status.type === 'loading' || Object.keys(validate()).length) return; setStatus({ type: 'loading', message: 'Submitting your registration…' }); try { const response = await fetch('/api/register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, email: form.email.trim(), contactNumber: form.contactNumber.trim() }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || 'Your registration could not be completed. Please try again.'); setStatus({ type: 'success', message: `Registration received. Your reference is ${data.registrationId}. Please monitor your email for an official invitation and venue entry pass.` }); setForm(initialForm); setErrors({}); } catch (error) { setStatus({ type: 'error', message: error instanceof Error ? error.message : 'Your registration could not be completed. Please try again.' }); } };
  if (status.type === 'success') return <section className="registration-success" aria-live="polite"><span className="success-symbol">✓</span><p className="registration-kicker">Registration received</p><h2>You are on the list<br /><em>for consideration.</em></h2><p>{status.message}</p><a className="registration-link-button" href="/">Return to the conference page <span>↗</span></a></section>;
  return <form className="conference-form" onSubmit={submit} noValidate>
    <div className="form-title-block"><p className="registration-kicker">Audience registration · 01</p><h1>1st HAPI Secular Philosophical Paper Conference <em>Registration Form</em></h1><p>Tell us who you are and how you would like to take part in this gathering of secular thinkers.</p></div>
    <div className="form-panel"><SectionHeading number="01">Personal information</SectionHeading><div className="form-grid two-up"><Field label="Last Name" name="lastName" value={form.lastName} onChange={update} error={errors.lastName} required autoComplete="family-name" /><Field label="First Name" name="firstName" value={form.firstName} onChange={update} error={errors.firstName} required autoComplete="given-name" /><Field label="Middle Name" name="middleName" value={form.middleName} onChange={update} autoComplete="additional-name" /><SelectField label="Gender" name="gender" value={form.gender} onChange={update} options={['Male', 'Female', 'Non-Binary', 'Prefer not to Say']} error={errors.gender} required /></div><Field label="Email Address" name="email" type="email" value={form.email} onChange={update} error={errors.email} required placeholder="Note that this is correct and accessible, we will reach out you via this address." autoComplete="email" /><Field label="Contact Number" name="contactNumber" type="tel" value={form.contactNumber} onChange={update} error={errors.contactNumber} required placeholder="e.g. +63 917 123 4567" autoComplete="tel" /></div>
    <div className="form-panel"><SectionHeading number="02">Where you are based</SectionHeading><p className="form-intro">Please provide the parts of your address needed for event communication.</p><div className="form-grid two-up"><Field label="Barangay" name="barangay" value={form.barangay} onChange={update} error={errors.barangay} required autoComplete="address-line2" /><Field label="Municipality / City" name="city" value={form.city} onChange={update} error={errors.city} required autoComplete="address-level2" /><Field label="Province" name="province" value={form.province} onChange={update} error={errors.province} required autoComplete="address-level1" /><Field label="Region" name="region" value={form.region} onChange={update} error={errors.region} required autoComplete="address-level1" /></div></div>
    <div className="form-panel"><SectionHeading number="03">Academic and community background</SectionHeading><TextareaField label="Institutional Affiliation" name="institutionalAffiliation" value={form.institutionalAffiliation} onChange={update} help="Please write the name of the university/s in which you are currently taking your degree or have finished your highest degree of accomplishment. For audience/participants, write N/A if you do not wish to disclose. Feel free to write more than one if necessary, separated by a comma." rows="3" /><TextareaField label="Degree and Program/s" name="degreeProgram" value={form.degreeProgram} onChange={update} help="e.g. Bachelor of Arts in Philosophy, Master of Divinity. For audience/participants, write N/A if you do not wish to disclose. Presenters are required to write their degree program they are currently in or had finished. Feel free to write more than one if necessary." rows="3" /><TextareaField label="Other Organizational/Institutional Affiliations" name="otherAffiliations" value={form.otherAffiliations} onChange={update} help="Separate by a comma if it is more than one. Write N/A if not applicable." rows="2" /></div>
    <div className="form-panel"><SectionHeading number="04">Your attendance</SectionHeading><div className="form-grid two-up"><SelectField label="Religious stance" name="religiousStance" value={form.religiousStance} onChange={update} options={religiousOptions} error={errors.religiousStance} required /><div className="form-field"><label htmlFor="attendingAs">I am Attending as<span className="required-mark">*</span></label><input id="attendingAs" name="attendingAs" value={form.attendingAs} readOnly /></div></div>{form.religiousStance === 'Other' && <Field label="Please specify" name="religiousStanceOther" value={form.religiousStanceOther} onChange={update} error={errors.religiousStanceOther} required />}<div className="attendance-options"><p className="field-label">Attendance Mode<span className="required-mark">*</span></p>{attendanceOptions.map((option) => <label className={`attendance-option${form.attendanceMode === option ? ' selected' : ''}`} key={option}><input type="radio" name="attendanceMode" value={option} checked={form.attendanceMode === option} onChange={update} /><span><b>{option}</b><small>{option === 'Onsite' ? 'At the Venue in The Ministry Lounge Bar & Cafe, Makati City' : 'Join the conference online'}</small></span></label>)}{errors.attendanceMode && <p className="field-error" role="alert">{errors.attendanceMode}</p>}</div></div>
    <div className="privacy-panel"><SectionHeading number="05">Personal information</SectionHeading><p>In compliance with Republic Act No. 10173, or the Data Privacy Act of 2012, HAPI is committed to protecting the personal information of its members. All personal data collected through this registration form will be used solely for membership administration, communication, and organizational activities. Such information will be handled with strict confidentiality and appropriate security measures, and will not be disclosed to third parties without the members consent, except as required by law.</p><label className={`consent-check${errors.consent ? ' has-error' : ''}`}><input type="checkbox" name="consent" checked={form.consent} onChange={update} /><span>I acknowledge the personal information notice above and consent to HAPI contacting me about this conference.</span></label>{errors.consent && <p className="field-error" role="alert">{errors.consent}</p>}</div>
    {status.type === 'error' && <div className="submission-error" role="alert">{status.message}</div>}<button className="submit-registration" type="submit" disabled={status.type === 'loading'}>{status.type === 'loading' ? 'Submitting registration…' : 'Submit Registration'}<span>↗</span></button>
  </form>;
}
